import { Photo } from '@/types/gallery';

export const photos: Photo[] = [
  {
    id: 'main-1',
    src: '/images/gallery/main/1.webp',
    alt: 'Main collection photo 1',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-2',
    src: '/images/gallery/main/2.webp',
    alt: 'Main collection photo 2',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-3',
    src: '/images/gallery/main/3.webp',
    alt: 'Main collection photo 3',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-4',
    src: '/images/gallery/main/4.webp',
    alt: 'Main collection photo 4',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-5',
    src: '/images/gallery/main/5.webp',
    alt: 'Main collection photo 5',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-6',
    src: '/images/gallery/main/6.webp',
    alt: 'Main collection photo 6',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-7',
    src: '/images/gallery/main/7.webp',
    alt: 'Main collection photo 7',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-8',
    src: '/images/gallery/main/8.webp',
    alt: 'Main collection photo 8',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-9',
    src: '/images/gallery/main/9.webp',
    alt: 'Main collection photo 9',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-10',
    src: '/images/gallery/main/10.webp',
    alt: 'Main collection photo 10',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-11',
    src: '/images/gallery/main/11.webp',
    alt: 'Main collection photo 11',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-12',
    src: '/images/gallery/main/12.webp',
    alt: 'Main collection photo 12',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'main-13',
    src: '/images/gallery/main/13.webp',
    alt: 'Main collection photo 13',
    title: 'Exploring perspectives on manhood, identity, and community',
    caption: 'Exploring perspectives on manhood, identity, and community',
    category: 'main',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-1',
    src: '/images/gallery/contemporary/1.webp',
    alt: 'Contemporary collection photo 1',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-2',
    src: '/images/gallery/contemporary/2.webp',
    alt: 'Contemporary collection photo 2',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-3',
    src: '/images/gallery/contemporary/3.webp',
    alt: 'Contemporary collection photo 3',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-4',
    src: '/images/gallery/contemporary/4.webp',
    alt: 'Contemporary collection photo 4',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-5',
    src: '/images/gallery/contemporary/5.webp',
    alt: 'Contemporary collection photo 5',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-6',
    src: '/images/gallery/contemporary/6.webp',
    alt: 'Contemporary collection photo 6',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-7',
    src: '/images/gallery/contemporary/7.webp',
    alt: 'Contemporary collection photo 7',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-8',
    src: '/images/gallery/contemporary/8.webp',
    alt: 'Contemporary collection photo 8',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-9',
    src: '/images/gallery/contemporary/9.webp',
    alt: 'Contemporary collection photo 9',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-10',
    src: '/images/gallery/contemporary/10.webp',
    alt: 'Contemporary collection photo 10',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-11',
    src: '/images/gallery/contemporary/11.webp',
    alt: 'Contemporary collection photo 11',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
    width: 1200,
    height: 1600,
  },
  {
    id: 'contemporary-12',
    src: '/images/gallery/contemporary/12.webp',
    alt: 'Contemporary collection photo 12',
    title: 'Present-day stories and experiences',
    caption: 'Present-day stories and experiences',
    category: 'contemporary',
